### ISSUE TITLE
[Bug]: No such file or directory: '/content/drive/MyDrive/AI/models/sd-v1-4.ckpt' => No interface running

### ISSUE THREAD

**Issue by echidne** [altryne/sd-webui-colab#21]
### What happened?

Hi,
I try for the first time to run the Colab page " Stable Diffusion WebUI 1.4!" . I had  error  at the last step where i have that message: 
Loading model from /content/drive/MyDrive/AI/models/sd-v1-4.ckpt
Traceback (most recent call last):
  File "scripts/webui.py", line 337, in <module>
    sd = load_sd_from_config(opt.ckpt)
  File "scripts/webui.py", line 148, in load_sd_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/AI/models/sd-v1-4.ckpt'
and when I try : "https://49817.gradio.app/" I have a 502 error message with "No interface is running right now"

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Colab

### Relevant log output

```shell
Traceback (most recent call last):
  File "scripts/webui.py", line 337, in <module>
    sd = load_sd_from_config(opt.ckpt)
  File "scripts/webui.py", line 148, in load_sd_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/AI/models/sd-v1-4.ckpt'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by altryne** [comment]
Doesn't seem like you have the model in your google drive, please follow instructions and upload the model (or use the checkbox provided and huggin face token and it'll download the model for you)

**Comment by Stradi** [comment]
You need to accept the model license in Hugging Face.

Go to the [model page](https://huggingface.co/CompVis/stable-diffusion-v-1-4-original).
