### ISSUE TITLE
[Bug]:  Model missing with error: "FileNotFoundError: [Errno 2] No such file or directory: '/content/sd-model/sd-v1-4.ckpt"

### ISSUE THREAD

**Issue by ktosox** [altryne/sd-webui-colab#28]
There seems to be an issues with acquiring the model, as it's not where the script expects it to be:

**Loading model from /content/sd-model/sd-v1-4.ckpt
Traceback (most recent call last):
  File "/content/stable-diffusion/scripts/webui.py", line 451, in <module>
    model,modelCS,modelFS,device, config = load_SD_model()
  File "/content/stable-diffusion/scripts/webui.py", line 399, in load_SD_model
    sd = load_sd_from_config(opt.ckpt)
  File "/content/stable-diffusion/scripts/webui.py", line 165, in load_sd_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file There seems to be an issues with acquiring the model:

The output stops with the error above.

It might be connected to this output that appears earlier on:

**/content/sd-model
Initialized empty Git repository in /content/sd-model/.git/
Updating origin
fatal: unable to access 'https://USER:https://huggingface.co/settings/tokens@huggingface.co/CompVis/stable-diffusion-v-1-4-original/': Port number ended with 'h'
error: Could not fetch origin
fatal: unable to access 'https://USER:https://huggingface.co/settings/tokens@huggingface.co/CompVis/stable-diffusion-v-1-4-original/': Port number ended with 'h'
/content
Cloning into '/content/stable-diffusion'...
remote: Enumerating objects: 2289, done.
remote: Counting objects: 100% (95/95), done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 2289 (delta 51), reused 76 (delta 45), pack-reused 2194
Receiving objects: 100% (2289/2289), 18.11 MiB | 20.68 MiB/s, done.
Resolving deltas: 100% (1313/1313), done.
/content/stable-diffusion**

Assistance in resolving this would be every much appreciated.

**Comment by ktosox** [comment]
Sorry. Now that I took a second look it seems like the "key" field was somehow overwritten.

Please ignore.
