### ISSUE TITLE
[Bug]: No module named 'gradio'

### ISSUE THREAD

**Issue by GothicOctopus** [altryne/sd-webui-colab#36]
### What happened?

Running normally.

Got to 3 - Launch WebUI.

Error message.

Traceback (most recent call last):
  File "scripts/webui.py", line 3, in <module>
    from frontend.frontend import draw_gradio_ui
  File "/content/stable-diffusion/frontend/frontend.py", line 1, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

Someone told me to tell it to 
!pip install gradio

No idea where to put that, or in what file tho.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Colab

### Relevant log output

```shell
Traceback (most recent call last):
  File "scripts/webui.py", line 3, in <module>
    from frontend.frontend import draw_gradio_ui
  File "/content/stable-diffusion/frontend/frontend.py", line 1, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Marcelgaviria7** [comment]
The same happens to me
